### PR TITLE
specify a start and end angle

### PR DESCRIPTION
**Pull request by waterskier2007**
Fixed formatting and added the ability to specify a start and end angle
for the button view

### CODE REVIEW

**Comment by 0ber** [comment]
thanks for good job, but angles work wrong
https://www.dropbox.com/s/m476gxtywq65e74/Screenshot%202016-03-03%2009.49.05.png?dl=0
please fix it

**Comment by surajrajudhopati** [comment]
Hi, is there a way to navigate to a different view controller from selected button after the rotation animation is performed?

**Comment by dancemonkey** [comment]
Has this merged yet? I'd love this capability but I don't see it enabled in the latest version. Nice job if you can work out the kinks.

**Comment by MinaAshna** [comment]
it is really handy, saved my day. please add it to the ASAP.

**Comment by gaming-hacker** [comment]
just clone the repo and cherry pick this PR, done.

**Pull request closed without merging**
